#pragma once


struct StreamerConstants
{
	int PIX_FMT_RGBA = AV_PIX_FMT_RGBA;
	int PIX_FMT_BGRA = AV_PIX_FMT_BGRA;
	int PIX_FMT_ARGB = AV_PIX_FMT_ARGB;
	int PIX_FMT_ABGR = AV_PIX_FMT_ABGR;
	int PIX_FMT_RGB24 = AV_PIX_FMT_RGB24;
	int PIX_FMT_BGR24 = AV_PIX_FMT_BGR24;

	int PIX_FMT_YUVJ422P = AV_PIX_FMT_YUVJ422P;
	int PIX_FMT_YUV422P = AV_PIX_FMT_YUV422P;

	int PIX_FMT_YUV420P = AV_PIX_FMT_YUV420P;
	int PIX_FMT_YUVJ420P = AV_PIX_FMT_YUVJ420P;
	int PIX_FMT_YUVA420P = AV_PIX_FMT_YUVA420P;
	int PIX_FMT_NV12 = AV_PIX_FMT_NV12;
	int PIX_FMT_NV21 = AV_PIX_FMT_NV21;
	int PIX_FMT_YUYV422 = AV_PIX_FMT_YUYV422;

	
	int SAMPLE_FMT_S16 = AV_SAMPLE_FMT_S16;
	int SAMPLE_FMT_FLTP = AV_SAMPLE_FMT_FLTP;
	int SAMPLE_FMT_FLT = AV_SAMPLE_FMT_FLT;


	int CODEC_ID_PNG = AV_CODEC_ID_PNG;
	int CODEC_ID_MJPEG = AV_CODEC_ID_MJPEG;
	int CODEC_ID_H264 = AV_CODEC_ID_H264;
	int CODEC_ID_AAC = AV_CODEC_ID_AAC;
	int CODEC_ID_RAWVIDEO = AV_CODEC_ID_RAWVIDEO;
	int CODEC_ID_PCM_S16LE = AV_CODEC_ID_PCM_S16LE;
	int CODEC_ID_PCM_F32LE = AV_CODEC_ID_PCM_F32LE;
};
